### ISSUE TITLE
caused by TypeError: Cannot read properties of undefined 

### ISSUE THREAD

**Issue by mbmoon** [veecode-platform/platform-backstage-plugins#38]
Hi,

I'm trying to configure Infracost plugin for Backstage. I have installed and configured frontend and backend plugins. Now when I try to register Kind: Infracost it produces an error after I had presses Analyze button:

> {"error":{"name":"InputError","message":"InputError: Processor InfracostEntityProcessor threw an error while postprocessing; caused by TypeError: Cannot read properties of undefined (reading 'baseUrl')"},"request":{"method":"POST","url":"/locations?dryRun=true"},"response":{"statusCode":400}}

My infracost.yaml

```
apiVersion: veecode.backstage.io/v1alpha1
kind: Infracost
metadata:
  name: demo-for-ifracost
spec:
  type: service
  lifecycle: experimental
  owner: group:default/my_group
  estimate:
      $text: ./infracost-base.json
```

**Comment by ValberJunior** [comment]
Hello,

As far as I can tell, you're trying to register a new kind of Infracost component in your backend, right? First, I'd ask you to check that the kind is added correctly in your backend.

https://github.com/veecode-platform/platform-backstage-plugins/tree/master/plugins/infracost-backend

```diff
 // ... in the app-config.yaml file
catalog:
 ...
  rules:
 -  - allow: [Component, System, API, Resource,Template, Location] 
 + - allow [Component, System, API, Resource, Template, Location, Infracost ]
  providers:
+    infracost:
+      default:
+        schedule:        
+          frequency: 
+            minutes: ${INFRACOST_PROVIDER_REFRESH_FREQUENCY}
+          timeout: 
+            minutes: ${INFRACOST_PROVIDER_TIMEOUT}
+          initialDelay:
+            seconds: ${INFRACOST_PROVIDER_INITIAL_DELAY}
```

In new backend:

`packages > backend > src > index.ts `:

```diff
import { createBackend } from '@backstage/backend-defaults';
+ import {catalogModuleInfracostProcessor, infracostPlugin} from '@veecode-platform/backstage-plugin-infracost-backend/alpha';

const backend = createBackend();

backend.add(import('@backstage/plugin-app-backend/alpha'));
backend.add(import('@backstage/plugin-proxy-backend/alpha'));
backend.add(import('@backstage/plugin-scaffolder-backend/alpha'));
backend.add(import('@backstage/plugin-techdocs-backend/alpha'));
...

+ backend.add(catalogModuleInfracostProcessor);
+ backend.add(infracostPlugin);


backend.start();
```

That would be kind:

```yaml
apiVersion: veecode.backstage.io/v1alpha1
kind: Infracost
metadata:
  name: "ec2-cluster-test"
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: FinOps
  lifecycle: experimental
  owner: "group:default/admin"
  estimate:
   $text: ./infracost-base.json
```

Remember, `infracost-base.json` needs to exist, so look, the process of generating this file is explained in the plujgin frontend documentation:

https://github.com/veecode-platform/platform-backstage-plugins/blob/master/plugins/infracost/README.md


---

Could you check that everything is in order?
