### ISSUE TITLE
CI/CD annotation with self-hosted gitlab

### ISSUE THREAD

**Issue by BornTKill** [veecode-platform/platform-backstage-plugins#4]
Dear,

I am using you pipeline plugin with my self hosted gitlab instance.
I was able to retrieve catalog-info but I cannot see CI/CD pipeline.

What annotation do I have to use ?

  annotations:
+    gitlab.com/project-slug: repo/test

**Comment by BornTKill** [comment]
OK finally find that I have to modify Entity Page to enable CI/CD with gitab.
But now I have this error 

An error has occurred
The requested scope is invalid, unknown, or malformed.

Is self-hosted gitlab supported ?

**Comment by ValberJunior** [comment]
Hello, how are you?

Well, let's go through the steps.
The annotation we should use so that the "CI-CD" tab maps your pipeline is as follows:
`gitlab.com/project-slug: xxx/project_name`

In the configuration of your `app-config.yaml`, make sure that the `integration`, `proxy` and `auth` information is correctly added, see examples of use with gitlab self-hosted:

`integrations`

```yaml
integrations:
  gitlab:
    - host: ${GITLAB_HOST_COMPANY} 
      token: ${GITLAB_TOKEN}
      apiBaseUrl: ${GITLAB_API_BASE_URL} # example: https://gitlab.company.com/api/v4 # According to the api version of your instance
```

`proxy`

```yaml
proxy:
  endpoints:
    '/gitlab/api':
      target: ${GITLAB_API_BASE_URL} # example: https://gitlab.company.com/api/v4
      allowedHeaders: ['Authorization', 'Content-Type']
      headers:
        Accept: application/json 
        Content-Type: application/json
```

and `auth`

```yaml
auth:
 environment: development
 providers:
   gitlab:
      development:
        clientId: ${ GITLAB_APP_CLIENT_ID}
        clientSecret: ${ GITLAB_APP_CLIENT_SECRET}
        audience: ${ GITLAB_APP_CLIENT_AUDIENCE} # example: https://gitlab.company.com
        callbackUrl: http://localhost:7007/api/auth/gitlab/handler/frame #optional
```


See our full documentation :arrow_right: [here](https://platform.vee.codes/plugin/Gitlab%20Pipelines/)

:warning: **I would like to ask you to check the version of our plugin that you are using, always update to the latest version.**


> I'd like to take this opportunity to invite you to send any suggestions or questions to our community in the comments. 💬 
>
> Join our community to resolve questions about our **Plugins**. We look forward to welcoming you! <br>
>
>    [Go to Community  🚀](https://github.com/orgs/veecode-platform/discussions)
